apiVersion: jenkins.io/v1
kind: Release
metadata:
  annotations:
    jenkins.io/chart-description: The Cheese App for Jenkins X
    jenkins.io/chart-repository: http://chartmuseum.jenkins-x.io
  creationTimestamp: "2019-03-28T16:08:27Z"
  labels:
    chart: jx-app-cheese-0.0.41
    jenkins.io/app-name: jx-app-cheese
    jenkins.io/app-version: 0.0.41
    jenkins.io/pluginCommand: jx-brie
  name: jx-app-cheese-0.0.41
spec: {}
